### ISSUE TITLE
Passing PooledConnection to a function

### ISSUE THREAD

**Issue by blasrodri** [sfackler/r2d2-postgres#10]
Hi! I will apologise, since it's likely that this issue has a simple answer. 
My goal is to understand how to use a pool of connections in order to pass them to functions that will run in several threads. 
To reproduce my problem, I took the snippet that is shown in the [README.md](#https://github.com/sfackler/r2d2-postgres/blob/master/README.md) and added a function that simply tries to get a pooled connection to work with. The gist is published here: https://gist.github.com/blasrodri/97b16271599ccd75c9fad2822dc2088f

And the error I get from the compiler is the following: 

```
   Compiling pool-conn v0.1.0 (file:///Users/rodrig/Desktop/pool-conn)
error: no method named `execute` found for type `r2d2::PooledConnection<T>` in the current scope
  --> src/main.rs:30:10
   |
30 |     conn.execute("INSERT INTO foo (bar) VALUES ($1)", &[&i]).unwrap();
   |          ^^^^^^^

error: aborting due to previous error

error: Could not compile `pool-conn`.
```

**Comment by sfackler** [comment]
Your `do_something` function places no constraints on what the connection type is. Is it a Postgres connection, or a Diesel connection, or a MySQL connection, or...? You can change it to take a `Pool<PostgresConnectionManager>`.

**Comment by blasrodri** [comment]
Perfect!! Exactly what I needed. Thanks!
