### ISSUE TITLE
Auto impl Send and Sync?

### ISSUE THREAD

**Issue by jeromegn** [sfackler/r2d2-postgres#13]
Hey there,

I'm wondering if `PostgresConnectionManager` could be considered `Send + Sync`?

I noticed other r2d2 connection managers are (I'm using the redis one, for example.) I assume it's dependent on the SslConnector also being Sync and Send, I think that would be fair.

**Comment by sfackler** [comment]
It is Send + Sync.

**Comment by jeromegn** [comment]
Whoops, you're right. It is implicitly Send and Sync. My bad.
