### ISSUE TITLE
Could not compile the example

### ISSUE THREAD

**Issue by esn01** [sfackler/r2d2-postgres#15]
I'm getting following errors trying to compile the example.
My Cargo.toml contents:

[dependencies]
postgres = "*"
r2d2_postgres = "*"

userxxx@machine01:~/data/work/rust/db/postgres/pgtest$ cargo build
   Compiling pgtest v0.1.0 (/home/userxxx/data/work/rust/db/postgres/pgtest)
error[E0432]: unresolved imports `postgres::NoTls`, `postgres::Client`
 --> src/main.rs:3:16
  |
3 | use postgres::{NoTls, Client};
  |                ^^^^^  ^^^^^^ no `Client` in the root
  |                |
  |                no `NoTls` in the root

error[E0433]: failed to resolve: use of undeclared type or module `r2d2`
  --> src/main.rs:12:16
   |
12 |     let pool = r2d2::Pool::new(manager).unwrap();
   |                ^^^^ use of undeclared type or module `r2d2`

warning: unused import: `Client`
 --> src/main.rs:3:23
  |
3 | use postgres::{NoTls, Client};
  |                       ^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `pgtest`.

To learn more, run the command again with --verbose.

**Comment by sfackler** [comment]
Don't use wildcard dependencies.

**Comment by esn01** [comment]
Thank you very much for your response.
I have changed the Cargo.toml dependencies and get following output after cargo build:

[dependencies]
postgres = "0.15"
r2d2_postgres = "0.15.0-rc.1"

cargo build
    Updating crates.io index
  Downloaded r2d2_postgres v0.15.0-rc.1
  Downloaded postgres v0.16.0-rc.1
  Downloaded tokio-postgres v0.4.0-rc.2
  Downloaded tokio v0.1.19
  Downloaded fallible-iterator v0.2.0
  Downloaded postgres-protocol v0.4.0
  Downloaded state_machine_future v0.2.0
  Downloaded tokio-threadpool v0.1.14
  Downloaded tokio-sync v0.1.5
  Downloaded generic-array v0.12.0
  Downloaded md5 v0.6.1
  Downloaded hmac v0.7.0
  Downloaded sha2 v0.8.0
  Downloaded rent_to_own v0.1.0
  Downloaded crypto-mac v0.7.0
  Downloaded digest v0.8.0
  Downloaded derive_state_machine_future v0.2.0
  Downloaded block-buffer v0.7.3
  Downloaded subtle v1.0.0
  Downloaded petgraph v0.4.13
  Downloaded syn v0.15.33
  Downloaded proc-macro2 v0.4.29
  Downloaded block-padding v0.1.4
  Downloaded byte-tools v0.3.1
  Downloaded darling v0.8.6
  Downloaded fixedbitset v0.1.9
  Downloaded ordermap v0.3.5
  Downloaded darling_core v0.8.6
  Downloaded ident_case v1.0.1
  Downloaded darling_macro v0.8.6
   Compiling proc-macro2 v0.4.29
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.33
   Compiling arrayvec v0.4.10
   Compiling lazy_static v1.3.0
   Compiling ident_case v1.0.1
   Compiling nodrop v0.1.13
   Compiling fnv v1.0.6
   Compiling byte-tools v0.3.1
   Compiling memoffset v0.2.1
   Compiling subtle v1.0.0
   Compiling fixedbitset v0.1.9
   Compiling ordermap v0.3.5
   Compiling memchr v2.2.0
   Compiling unicode-segmentation v1.2.1
   Compiling lazycell v1.2.1
   Compiling slab v0.4.2
   Compiling futures v0.1.26
   Compiling opaque-debug v0.2.2
   Compiling rent_to_own v0.1.0
   Compiling md5 v0.6.1
   Compiling percent-encoding v1.0.1
   Compiling fallible-iterator v0.2.0
   Compiling crossbeam-utils v0.6.5
   Compiling tokio-trace-core v0.1.0
   Compiling block-padding v0.1.4
   Compiling heck v0.3.1
   Compiling net2 v0.2.33
   Compiling num_cpus v1.10.0
   Compiling generic-array v0.12.0
   Compiling base64 v0.10.1
   Compiling petgraph v0.4.13
   Compiling mio v0.6.16
   Compiling crossbeam-epoch v0.7.1
   Compiling crossbeam-queue v0.1.2
   Compiling crypto-mac v0.7.0
   Compiling digest v0.8.0
   Compiling block-buffer v0.7.3
   Compiling crossbeam-deque v0.7.1
   Compiling sha2 v0.8.0
   Compiling hmac v0.7.0
   Compiling quote v0.6.12
   Compiling mio-uds v0.6.7
   Compiling postgres-protocol v0.4.0
   Compiling tokio-executor v0.1.7
   Compiling tokio-sync v0.1.5
   Compiling tokio-io v0.1.12
   Compiling futures-cpupool v0.1.8
   Compiling tokio-threadpool v0.1.14
   Compiling tokio-current-thread v0.1.6
   Compiling tokio-timer v0.2.10
   Compiling tokio-codec v0.1.1
   Compiling tokio-reactor v0.1.9
   Compiling tokio-fs v0.1.6
   Compiling tokio-tcp v0.1.3
   Compiling tokio-uds v0.2.5
   Compiling tokio-udp v0.1.3
   Compiling tokio v0.1.19
   Compiling darling_core v0.8.6
   Compiling darling_macro v0.8.6
   Compiling darling v0.8.6
   Compiling derive_state_machine_future v0.2.0
   Compiling state_machine_future v0.2.0
   Compiling tokio-postgres v0.4.0-rc.2
   Compiling postgres v0.16.0-rc.1
   Compiling r2d2_postgres v0.15.0-rc.1
   Compiling pgtest v0.1.0 (/home/slawek/data/work/rust/db/postgres/pgtest)
error[E0432]: unresolved imports `postgres::NoTls`, `postgres::Client`
 --> src/main.rs:3:16
  |
3 | use postgres::{NoTls, Client};
  |                ^^^^^  ^^^^^^ no `Client` in the root
  |                |
  |                no `NoTls` in the root

error[E0433]: failed to resolve: use of undeclared type or module `r2d2`
  --> src/main.rs:12:16
   |
12 |     let pool = r2d2::Pool::new(manager).unwrap();
   |                ^^^^ use of undeclared type or module `r2d2`

warning: unused import: `Client`
 --> src/main.rs:3:23
  |
3 | use postgres::{NoTls, Client};
  |                       ^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `pgtest`.

**Comment by sfackler** [comment]
You need to use postgres 0.16.0-rc.1. You also need to depend on the r2d2 crate.

**Comment by esn01** [comment]
It builds with

[dependencies]
r2d2 = "0.8.4"
postgres = "0.16.0-rc.1"
r2d2_postgres = "0.15.0-rc.1"

Thank you very much!

p.s.
Would not it be helpful to extend the readme  file?

**Comment by rokit** [comment]
A working example would be much appreciated. I cannot compile it either, even after adding the r2d2 crate: the `#[non_exhaustive]` attribute is an experimental feature.
https://github.com/rokit/r2d2-postgres-example-test

**Comment by sfackler** [comment]
You need to update your compiler to 1.40.0.
