### ISSUE TITLE
Caching Statements?

### ISSUE THREAD

**Issue by bedax** [sfackler/r2d2-postgres#16]
Hello, I am wondering if it's possible to cache statements while using this connection pool? 

As I understand it, caching support was removed from the underlying postgres library as Statements are now 'static and so can be cached externally. However, Statements must be used with the same Connection that created them, and so if I build an external Statement Cache, then I have to have a Cache for each Connection in the Pool. Which would be fine, but when I get a Connection from the Pool I don't know which Connection I've got and so I can't retrieve its Statement from the Cache. Am I missing something, or is caching not really possible when using a connection pool?

**Comment by sfackler** [comment]
Ah yeah, I'd intended to handle this by adding a `TypeMap` to `CachedConnection` here so you could stash things like prepared statements along side the connection. I'll push up a change.

**Comment by bedax** [comment]
Brilliant, that sounds good :+1:

**Comment by bedax** [comment]
Great work! Thanks for this, and for your work in general :+1:
