### ISSUE TITLE
Update Postgres version to 0.17.0-alpha.2

### ISSUE THREAD

**Issue by dbettin** [sfackler/r2d2-postgres#18]
Are there any plans to support the latest version of Postgres?  In its current state, I am unsuccessfully able to use the Postgres UUID (v0.8) serialization support on alpha.1.

**Comment by nghenglim** [comment]
Will be great to have 0.17.0-alpha.2, currently I have to manually refer to cloned repo path for alpha.2

**Comment by sfackler** [comment]
Done! Thanks for the reminder.
