### ISSUE TITLE
postgres database connection

### ISSUE THREAD

**Issue by yonathanYPP** [sfackler/r2d2-postgres#21]
i have searched for the complete r2d2_postgres connection format, but got nothing, how i declare the connection to the database,because the example only define "host=localhost user=postgres", i really appreciate for any help, thanks

**Comment by sfackler** [comment]
It uses the same format as the postgres crate: https://docs.rs/postgres/0.17.2/postgres/config/struct.Config.html

**Comment by yonathanYPP** [comment]
any suggestion for query transaction using r2d2_postgres? Because r2d2_postgres doesn't have prepare

**Comment by sfackler** [comment]
https://docs.rs/postgres/0.17.2/postgres/struct.Client.html#method.prepare
