### ISSUE TITLE
Postgres 0.18 release?

### ISSUE THREAD

**Issue by palfrey** [sfackler/r2d2-postgres#25]
The Cargo.toml has been updated here, but I'm not seeing anything in https://crates.io/crates/r2d2_postgres ?

**Comment by palfrey** [comment]
Ah, whoops. Reading the wrong bit. Commit mentioned "0.17 release", and now realised that was Postgres 0.17. Any chance of a release with Postgres 0.18?

**Comment by sfackler** [comment]
Done!

**Comment by palfrey** [comment]
Looks like this broke the build, as tokio uses `u64::MAX` which only got introduced in 1.43.0 (see https://doc.rust-lang.org/std/primitive.u64.html#associatedconstant.MAX)
