### ISSUE TITLE
Transaction support?

### ISSUE THREAD

**Issue by kostaskol** [sfackler/r2d2-postgres#26]
The postgres crate supports [transactions](https://docs.rs/postgres/0.19.0/postgres/struct.Transaction.html) via the `Transaction` struct which has a similar interface to `Client`.

Is there any way to get `Transaction` objects instead of `Client`s out of the pool?

**Comment by sfackler** [comment]
You can get a client out of the pool and then make a transaction with it.

**Comment by kostaskol** [comment]
Oh jeez, I can't believe I missed that.. Thanks for your time and sorry for the trouble
