### ISSUE TITLE
Switch/configure is_valid query?

### ISSUE THREAD

**Issue by wseaton** [sfackler/r2d2-postgres#28]
Hello, I have a legacy database that I'm looking to use `r2d2-postgres` w/ ([Teiid](https://teiid.io/)) that implements a PostgreSQL compatible API. Unfortunately it doesn't support passing in blank queries as described by the PostgreSQL spec.

Debugging thread here: https://github.com/sfu-db/connector-x/issues/107

Would you be open to switching the probe query for `is_valid` to something more standard, like `SELECT 1;`, or at least make this configurable? This would allow me (and others) to retain connection pooling functionality in that case. 

I noticed `SELECT 1;` is actually what is recommended upstream in r2d2 for connection pool implementors, and understand the empty query is probably slightly faster round trip.

Thanks!

**Comment by sfackler** [comment]
Sure, `SELECT 1` seems reasonable to me.

**Comment by wseaton** [comment]
@sfackler now that this is merged, do you have plans to cut a patch release?

**Comment by sfackler** [comment]
Done!
