### ISSUE TITLE
TlsMode::Require format. 

### ISSUE THREAD

**Issue by tomt1664** [sfackler/r2d2-postgres#32]
Using the old version, how can I connect to a db requiring tls/ssl? 
Can postgres_openssl::MakeTlsConnector be used?

**Comment by sfackler** [comment]
"the old version"?

**Comment by tomt1664** [comment]
As I understand it, in the current release, the second argument of `PostgresConnectionManager::new` can take either   `NoTls` or a `MakeTlsConnector` object, like:

```   
let mut builder = SslConnector::builder(SslMethod::tls()).unwrap();
builder.set_ca_file(pg_cert_loc).expect("failed to load certificate");
let connector = MakeTlsConnector::new(builder.build());

let manager = PostgresConnectionManager::new( url.parse().unwrap(), connector);
```

(however, I get the following error when trying this:
```
#21 738.5    --> server/src/storage/db.rs:185:67
#21 738.5     |
#21 738.5 185 |         let manager = PostgresConnectionManager::new(url.clone(), tls_connector)?;
#21 738.5     |                                                                   ^^^^^^^^^^^^^ the trait `MakeTlsConnect<Socket>` is not implemented for `MakeTlsConnector`
```
)

However, the code I am trying to get to connect to a postgres DB over ssl is using a previous/older version of r2d2_postgres from `rocket_contrib = { version = "0.4.8", default-features = false,features = ["json","postgres_pool"] }` where the second argument of `PostgresConnectionManager::new` is a `TlsMode::None` or `TlsMode::Require(...)) object. It's not clear how to specify the connector as an argument to `Require(...)` - everything I've tried hasn't worked. 

Appologies if I am missing something obvious.

**Comment by sfackler** [comment]
That version of r2d2-postgres is over 5 years old, and is not supported.
