### ISSUE TITLE
How to Use With SslMode::Require?

### ISSUE THREAD

**Issue by SecurityInsanity** [sfackler/r2d2-postgres#7]
I'm just curious what's the recommended way to use r2d2-postgres with SslMode::Require, or Preferred? I've been racking my head around this for awhile, and I assume it's something dumb that I'm just not thinking of.

I can successfully get a connection over TLS with the normal postgres crate w/ OpenSSL Contexts, but I'm not sure how to get it to work within this crate. Any insight would be very helpful. If you need to see code I've tried I'd be happy to drop it in.

**Comment by sfackler** [comment]
It should be pretty similar. If you have something like this with Postgres directly:

```rust
let mut ctx = SslContext::new(SslMethod::Sslv23).unwrap();
// configure ctx ...
let conn = Connection::connect("postgres://localhost/foobar", SslMode::Require(&ctx)).unwrap();
// ...
```

You'd just change it to:
```rust
let mut ctx = SslContext::new(SslMethod::Sslv23).unwrap();
// configure ctx ...
let config = Default::default();
let manager = PostgresConnectionManager::new("postgres://localhost/foobar", SslMode::Require(Box::new(ctx))).unwrap();
let pool = Pool::new(config, manager).unwrap();
// ...
```

**Comment by SecurityInsanity** [comment]
Hmmm that's similar to what I tried, but am still getting an error on creating the manager:
```
let mut context = SslContext::new(SslMethod::Tlsv1);
// configured ctx...
let manager = PostgresConnectionManager::new("postgres://localhost/foobar", SslMode::Require(Box::new(context))).unwrap();
```

However this results in:
```
src/main.rs:32:98: 32:115 error: the trait bound `std::result::Result<openssl::ssl::SslContext, openssl::ssl::error::SslError>: postgres::io::NegotiateSsl` is not satisfied [E0277]
src/main.rs:32     let manager = PostgresConnectionManager::new("postgres://localhost/foobar", SslMode::Require(Box::new(context))).unwrap();
                                                                                                                ^~~~~~~~~~~~~~~~~
src/main.rs:32:98: 32:115 help: run `rustc --explain E0277` to see a detailed explanation
src/main.rs:32:98: 32:115 note: required for the cast to the object type `postgres::io::NegotiateSsl + Send + Sync + 'static`
error: aborting due to previous error
```

**Comment by sfackler** [comment]
`SslContext::new` returns a Result. You'll need to get the SslContext out of it.

Also note that openssl's default configuration is super insecure. It in particular doesn't validate the server's certificate at all.

**Comment by SecurityInsanity** [comment]
Yea I'm just trying to set up a base case before giving it my configuration options. I have every intention to change it.

Weird I didn't catch that unwrap for the Result.

However even unwrapping it results in an error:
```
src/main.rs:33:98: 33:115 error: the trait bound `openssl::ssl::SslContext: postgres::io::NegotiateSsl` is not satisfied [E0277]
src/main.rs:33     let manager = PostgresConnectionManager::new("postgres://localhost/foobar", SslMode::Require(Box::new(context))).unwrap();
                                                                                                                ^~~~~~~~~~~~~~~~~
src/main.rs:33:98: 33:115 help: run `rustc --explain E0277` to see a detailed explanation
src/main.rs:33:98: 33:115 note: required for the cast to the object type `postgres::io::NegotiateSsl + Send + Sync + 'static`
error: aborting due to previous error
error: Could not compile `warden`.
```

Perhaps I'm just doing something ignorant, or not seeing something obvious (if I am sorry!)

**Comment by sfackler** [comment]
Ah, you'll need to activate the `openssl` feature of postgres:

```toml
[dependencies]
postgres = { version = "0.11", features = ["openssl"] }
```

**Comment by SecurityInsanity** [comment]
Ah Yep. Forgetting to enable that on a new Project. Filing this under "Things to remember not to be ignorant about". Much appreciated. :bow:

**Comment by sfackler** [comment]
Cool!

When looking into the security, one thing to note is that the built in implementation for OpenSSL doesn't currently do hostname verification. This'll change in the next 0.12 release of rust-postgres, but in the meantime, you might want to consider copy-pasting this into your project: https://github.com/sfackler/rust-postgres/blob/breaks/src/io/openssl.rs

**Comment by SecurityInsanity** [comment]
Ah that's a _very good_ caveat to know. Thanks much for the pointer on that.

**Comment by oneilk** [comment]
I know this is very old, but I wad wondering if anyone could help me out with this same thing. Let me preface this with I have zero experience with Rust. 

We use Canvas and I am using this https://github.com/instructure/canvas-data-loader to replicate canvas' database to our database. I have this all working (I can get it to download to a local database), but now the hiccup is having it connect to database which requires SslMode::require.

I've managed to pinpoint where I need to turn on SslMode::require.. https://github.com/instructure/canvas-data-loader/blob/master/src/db_client.rs#L83 but have absolutely no idea how to go about it.

Any insight is so much appreciated.

**Comment by sfackler** [comment]
This issue is 4 years old - the sslmode is now configured in the connection URL.

**Comment by oneilk** [comment]
I still get 

```ERROR 2020-08-20T21:22:14Z: r2d2: database error: FATAL: no pg_hba.conf entry for host "17.150.208.127", user "canvas_data_loader", database "canvas_data", SSL off```

with

```let manager = PostgresConnectionManager::new("postgresql://user:pw@host:5432/canvas_data?sslmode=verify-ca", TlsMode::None);```

**Comment by sfackler** [comment]
You appear to be using an old version of the library. In that case `TlsMode` acts like `SslMode`.
